### PR TITLE
Fixes poor code

### LINKED ISSUE #19: Fixes
- [x] Fix gradle script
- [x] Dont work with scheduled executor service

### PR DESCRIPTION
**Pull request by IdanKoblik**
Restructured code design while maintaining abstract code structure.

- [paper] New module that impl adventure api
- [adventure] Now adventure module used as abstract module for all minecraft impl's
- [shared] `AbstractSong` has been moved to `shared` module

Fix gradle script

Closes #19

### CODE REVIEW

File: adventure/src/main/java/com/github/idankoblik/jukebox/KyoriSong.java [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+import java.util.concurrent.CompletableFuture;
+
+/**
+ * Abstract base class representing a musical song.
+ * <p>
+ * This class provides the foundation for creating songs with audience interaction
+ * and sound management.
+ * </p>
+ */
+public abstract class KyoriSong extends AbstractSong {
```
Comment (IdanKoblik) [inline adventure/src/main/java/com/github/idankoblik/jukebox/KyoriSong.java:22]: Generic

**Comment by IdanKoblik** [comment]
The notes are played too fast
